core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from core import views

app_name = 'core'

urlpatterns = [
    path('', views.TeamListView.as_view(), name='teams'),
	path('team-details/<int:pk>/', views.TeamDetailView.as_view(), name='details'),
	path('player/<int:pk>/', views.PlayerDetailView.as_view(), name='player'),
	path('matches/', views.MatchView.as_view(), name='matches'),
	path('match/<int:pk>/', views.MatchView.as_view(), name='team-match'),
	path('points/', views.PointsView.as_view(), name='points'),
	path('points/<int:pk>/', views.PointsView.as_view(), name='team-point'),

	# ===============================================================================
	# ================================== API ========================================
	# ===============================================================================

	path('api/team-list/', views.ApiTeamListView.as_view(), name='api-teams'),
	path('api/team-details/<int:pk>/', views.ApiTeamDetailView.as_view(), name='api-details'),
	path('api/player/<int:pk>/', views.ApiPlayerView.as_view(), name='api-player'),
	path('api/matches/', views.ApiMatchScheduleView.as_view(), name='api-match'),
	path('api/match/<int:pk>/', views.ApiMatchScheduleView.as_view(), name='api-team-match'),
	path('api/points/', views.ApiPointsView.as_view(), name='api-points'),
	path('api/points/<int:pk>/', views.ApiPointsView.as_view(), name='api-team-point'),
]

cricket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core_app'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cricket/templates/matches.html
{% load i18n %}

{% block title %}
    {% trans "Match Schedule" %}

    {% if team %}
        <p>TEAM: {{team.title}}</p>
        <p>
            <a href="{% url 'core:teams' %}">Teams</a>&nbsp;&nbsp;&nbsp;
            <a href="{% url 'core:team-point' team.id %}">Points</a>
        </p>
    {% else %}
        <p>
            <a href="{% url 'core:teams' %}">Teams</a>&nbsp;&nbsp;&nbsp;
            <a href="{% url 'core:points' %}">Points</a>
        </p>
    {% endif %}
{% endblock %}

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    th, td {
        padding: 5px;
        text-align: left;
    }
</style>

{% block content %}

    {% if matches %}
        <table>
            <thead>
                <tr>
                    <th>{% trans "Date" %}</th>
                    <th>{% trans "Match Details" %}</th>
                    <th>{% trans "Time" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for match in matches %}
                    <tr>
                        <td>{{match.match_date}}</td>
                        <td>{{match.team}} VS {{match.match_with}}</td>
                        <td>{{match.match_time}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>{% trans "No Match have been made yet." %}</p>
    {% endif %}

{% endblock content %}

cricket/templates/player.html
{% load i18n %}

{% block title %}
    {% trans "Player History" %}

    <p>TEAM: {{player.team.title}}</p>
    <p><img src="{{player.full_path}}" width="48px"></p>
    <p>NAME: {{player.full_name|default:"-"}}</p>
    <p>
        <a href="{% url 'core:teams' %}">Teams</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'core:details' player.team.id %}">Team Players</a>
    </p>
{% endblock %}

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    th, td {
        padding: 5px;
        text-align: left;
    }
</style>

{% block content %}

    {% if details %}
        <table>
            <thead>
                <tr>
                    <th>{% trans "Match" %}</th>
                    <th>{% trans "Runs" %}</th>
                    <th>{% trans "Highest Scores" %}</th>
                    <th>{% trans "Hundreds" %}</th>
                    <th>{% trans "Fiftes" %}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{details.total_match}}</td>
                    <td>{{details.total_run}}</td>
                    <td>{{details.highest_score}}</td>
                    <td>{{details.total_centuries}}</td>
                    <td>{{details.total_fifties}}</td>
                </tr>
            </tbody>
        </table>
    {% else %}
        <p>{% trans "No Player History have been made yet." %}</p>
    {% endif %}

{% endblock content %}

cricket/templates/points.html
{% load i18n %}

{% block title %}
    {% trans "Points Table" %}

    {% if team %}
        <p>TEAM: {{team.title}}</p>
        <p>
            <a href="{% url 'core:teams' %}">Teams</a>&nbsp;&nbsp;&nbsp;
            <a href="{% url 'core:team-match' team.id %}">Schedule</a>
        </p>
    {% else %}
        <p>
            <a href="{% url 'core:teams' %}">Teams</a>&nbsp;&nbsp;&nbsp;
            <a href="{% url 'core:matches' %}">Schedule</a>
        </p>
    {% endif %}
{% endblock %}

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    th, td {
        padding: 5px;
        text-align: left;
    }
</style>

{% block content %}

    {% if points %}
        <table>
            <thead>
                <tr>
                    <th>{% trans "Teams" %}</th>
                    <th>{% trans "Match" %}</th>
                    <th>{% trans "Won" %}</th>
                    <th>{% trans "Lost" %}</th>
                    <th>{% trans "Tied" %}</th>
                    <th>{% trans "NR" %}</th>
                    <th>{% trans "PTs" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for point in points %}
                    <tr>
                        <td>{{point.team}}</td>
                        <td>{{point.match}}</td>
                        <td>{{point.won|default:"0"}}</td>
                        <td>{{point.lose|default:"0"}}</td>
                        <td>{{point.tied|default:"0"}}</td>
                        <td>{{point.nr|default:"0"}}</td>
                        <td>{{point.pts|default:"0"}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>{% trans "No Points have been made yet." %}</p>
    {% endif %}

{% endblock content %}

cricket/templates/team-detail.html
{% load i18n %}

{% block title %}
    {% trans "Players List" %}
    <p>TEAM: {{team.title}}</p>

    <p>
        <a href="{% url 'core:teams' %}">Teams</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'core:team-match' team.id %}">Schedule</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'core:team-point' team.id %}">Points</a>
    </p>
{% endblock %}

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    th, td {
        padding: 5px;
        text-align: left;
    }
</style>

{% block content %}

    {% if players %}
        <table>
            <thead>
                <tr>
                    <th>{% trans "Image" %}</th>
                    <th>{% trans "First Name" %}</th>
                    <th>{% trans "Last Name" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for player in players %}
                    <tr>
                        <td><p><img src="{{player.full_path}}" width="48px"></p></td>
                        <td><a href="{% url 'core:player' player.id %}">{{player.first_name}}</a></td>
                        <td>{{player.last_name|default:"-" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>{% trans "No Players in this team" %}</p>
    {% endif %}

{% endblock content %}

cricket/templates/team-list.html
{% load i18n %}

{% block title %}
    {% trans "Cricket Team List" %}

    <p>
        <a href="{% url 'core:matches' %}">Match Schedule</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'core:points' %}">Match Points</a>
    </p>
{% endblock %}


<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    th, td {
        padding: 5px;
        text-align: left;
    }
</style>

{% block content %}

    <h1>{{message}}</h1>

    {% if teams %}
        <table>
            <thead>
                <tr>
                    <th>{% trans "Team Name" %}</th>
                    <th>{% trans "Logo" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for team in teams %}
                    <tr>
                        <td><a href="{% url 'core:details' team.id %}">{{ team.title|default:"-" }}</a></td>
                        <td><p><img src="{{ team.full_path }}" width="80px"></p></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- <a href="">Points Table</a> -->
    {% else %}
        <p>{% trans "No Cricket Teams have been made yet." %}</p>
    {% endif %}

{% endblock content %}